[package]
authors = ["hsjobeki <hsjobeki@gmail.com>", "jD91mZM2 <me@krake.one>"]
description = ""
edition = "2021"
license = "MIT"
name = "tnix"
version = "0.11.0"

[dependencies]
rnix = "0.11.0"
rowan = "0.15.0"

[dev-dependencies]
criterion = "0.3.0"
expect-test = "1.4.0"
