[book]
authors = ["@hsjobeki:Johannes Kirschbauer"]
language = "en"
multilingual = false
src = "src"
title = "Nix Types - Convention considerations"

[output.html]
mathjax-support = true
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["theme/highlight-dark.css"]
git-repository-url = "https://github.com/hsjobeki/nix-types"
git-repository-icon = "fa-code-fork"
